server:
  port: 8082

spring:
  application:
    name: employees-frontend

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
    org.springframework.security: DEBUG

employees:
  backend-url: http://localhost:8081
