server:
  port: 8082

spring:
  application:
    name: employees-frontend
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: employees-frontend
            authorization-grant-type: authorization_code
            scope: openid,email,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/employees
            user-name-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
    org.springframework.security: DEBUG

employees:
  backend-url: http://localhost:8081
