server:
  port: 8081

spring:
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/db-changelog.yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
    org.springframework.security: DEBUG
